# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - name: Checkout SmartSlice
      uses: actions/checkout@v2        
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Build
      run: 
        wget https://github.com/Ultimaker/Cura/releases/download/4.7.1/Ultimaker_Cura-4.7.1.AppImage
  
    - name: smartslice tests
      run: |
        ls
        chmod a+x Ultimaker_Cura-4.7.1.AppImage
        ./Ultimaker_Cura-4.7.1.AppImage --appimage-extract
        cd squashfs-root
        ls
        

