# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    container: ultimaker/cura-build-environment 
    
    steps:
    - name: Checkout SmartSlice
      uses: actions/checkout@v2        

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: Ultimaker/Cura
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Build
      run: 
        docker build --build-arg CURA_BUILD_ENV_BUILD_TYPE=Release 
        docker/build.sh  
  
    - name: smartslice tests
      run: |
         python cura_app.py --headless    

