# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
    - name: Checkout SmartSlice
      uses: actions/checkout@v2
     
    - name: checkout b  
      run: git checkout r20.1-unittest-runner
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Build
      run: |
        wget https://github.com/Ultimaker/Cura/releases/download/4.7.1/Ultimaker_Cura-4.7.1.AppImage
        sudo apt-get install xvfb mesa-utils

    - name: Get pywim and py3mf
      run: |
        git clone https://github.com/tetonsim/pywim.git
        git clone https://github.com/tetonsim/py3mf.git

    - name: move pywim and 3mf to ss
      run: |
        mv pywim/pywim SmartSlicePlugin/3rd-party/cpython-common
        mv py3mf/threemf SmartSlicePlugin/3rd-party/cpython-common

    - name: Extract and patch
      run: |
        chmod a+x Ultimaker_Cura-4.7.1.AppImage
        ./Ultimaker_Cura-4.7.1.AppImage --appimage-extract
        mv cura.patch $(pwd)/squashfs-root/usr/bin
        cd squashfs-root/usr/bin
        patch < cura.patch
    
    - name: move smart slice into cura plugins
      run: mv SmartSlicePlugin squashfs-root/usr/bin/plugins/plugins
    
    - name: Tests
      timeout-minutes: 1
      run: |
        cd squashfs-root/usr/bin
        export PYTHONPATH="$(pwd)/lib/python3.5"
        export QT_PLUGIN_PATH="$(pwd)/qt/plugins"
        export QML2_IMPORT_PATH="$(pwd)/qt/qml"
        export QT_QPA_FONTDIR=/usr/share/fonts
        export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb

        # Use the openssl.cnf packaged in the AppImage
        export OPENSSL_CONF="$(pwd)/openssl.cnf"
        
        cd plugins/plugins/SmartSlicePlugin/tests
        python3.5 run.py

#        xvfb-run ./AppRun
        
    - name: get Log
      run: |
        cd .local/share/cura
        ls

      # :80 -screen 0 1400x900x24 -ac +extension GLX +render -noreset
        

