# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    
jobs:
  build:
    container:  ultimaker/cura-build-environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SmartSlice
      uses: actions/checkout@v2
      with:
         ref: r20.2-unittest-runner


    - name: Docker build
    - uses: openrndr/setup-opengl@v1
    - run: |
        xvfb-run glxinfo
        git clone https://github.com/colman-hartinger/Cura-1.git
        ls
        cd Cura-1
        docker build --tag=cura:1.0 .
        docker run cura:1.0
      #  sudo apt-get update && sudo apt-get install build-essential


#     - name: Build
#       run: |
#         wget https://github.com/Ultimaker/Cura/releases/download/4.6.2/Ultimaker_Cura-4.6.2.AppImage
#         sudo apt-get install xvfb mesa-utils  python-xml
        
#     - name: Get pywim and py3mf
#       run: |
#         git clone https://github.com/tetonsim/pywim.git
#         git clone https://github.com/tetonsim/py3mf.git

#     - name: move pywim and 3mf to ss
#       run: |
#         mv pywim/pywim SmartSlicePlugin/3rd-party/cpython-common
#         mv py3mf/threemf SmartSlicePlugin/3rd-party/cpython-common

#     - name: Extract and patch
#       run: |
#         chmod a+x Ultimaker_Cura-4.6.2.AppImage
#         ./Ultimaker_Cura-4.6.2.AppImage --appimage-extract
#     #    mv cura.patch $(pwd)/squashfs-root/usr/bin
#      #   cd squashfs-root/usr/bin
#    #     patch < cura.patch
    
#     - name: move smart slice into cura plugins
#       run: mv SmartSlicePlugin squashfs-root/usr/bin/plugins/plugins
    
#     - name: Tests
#       timeout-minutes: 5
#       run: |
#         cd squashfs-root/usr/bin
#         export PYTHONPATH=$(pwd)/lib/python3.5
#         pip install numpy
#         pip install six
#         export QT_PLUGIN_PATH=$(pwd)/qt/plugins
#         export QML2_IMPORT_PATH=$(pwd)/qt/qml
#         export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)
        

#         cd plugins/plugins/SmartSlicePlugin/tests
#         xvfb-run python3.5 run.py

        

